version: "3.8"

services:
  frontend:
    container_name: codeconvert-container
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    environment:
      - REACT_APP_API_URL=http://backend-api:5000

  # backend-api:
  #   container_name: my-backend-container  # Custom container name for backend
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=mysql://user:password@db:3306/mydatabase
  #   depends_on:
  #     - db

  # db:
  #   container_name: my-database-container  # Custom container name for database
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
# volumes:
#   db_data:
