pipeline:
  name: myfrontend
  identifier: myfrontend
  projectIdentifier: uac
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerconnector
                    image: node:20.9.0-alpine3.18
                    shell: Sh
                    command: |-
                      echo "execution started"
                      ls
                      echo "execution completed"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubemine
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: account.harnessImage
              os: Linux
        delegateSelectors:
          - kubernetes-delegate
