pipeline:
  name: myfrontend
  identifier: myfrontend
  projectIdentifier: uac
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: clone repo
        identifier: clone_repo
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: npm install
                  identifier: npm_install
                  spec:
                    shell: Sh
                    command: ls
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
